stages:
  - build
  - push
  - blackduck

build:
  stage: build
  script:
    - docker build -t dcr.faked.org/gitlab-ci/android:${CI_COMMIT_SHORT_SHA} .
    
 blackduck_scan:
  stage: blackduck
  script:
    - bash <(curl -s https://blackducksoftware.github.io/blackduck-docker-inspector/blackduck-docker-inspector.sh) {Black Duck Docker Inspector arguments}


push_latest:
  stage: push
  only:
    - master
  script:
    - docker tag dcr.faked.org/gitlab-ci/android:${CI_COMMIT_SHORT_SHA} dcr.faked.org/gitlab-ci/android:latest
    - docker push dcr.faked.org/gitlab-ci/android:latest

push_tag:
  stage: push
  only:
    - tags
  script:
    - docker tag dcr.faked.org/gitlab-ci/android:${CI_COMMIT_SHORT_SHA} dcr.faked.org/gitlab-ci/android:${CI_COMMIT_TAG}
    - docker push dcr.faked.org/gitlab-ci/android:${CI_COMMIT_TAG}
